server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mysuite-service
          uri: http://localhost:8091
          predicates:
            - Path=/mysuite/**
        - id: infinity-service
          uri: lb://infinity-service
          predicates:
            - Path=/infinity/**
        - id: servicioConecta-service
          uri: lb://servicioConecta-service
          predicates:
            - Path=/servicioConecta/**
